app:
  name: bonfairplace-main
  version: 0.0.307
values: |    
  fullnameOverride: bonfairplace-main
  domain: bandbsolution.com.ua
  ingress.enabled: true
  ingress.rules[0].host: bandbsolution.com.ua
  ingress.rules[0].http.paths[0].path: /
  ingress.rules[0].http.paths[0].pathType: ImplementationSpecific
  ingress.rules[0].http.paths[0].backend.service.name: visit-card
  ingress.rules[0].http.paths[0].backend.service.port.number: 80
  ingress.annotations.kubernetes\\.io/ingress\\.global-static-ip-name: visit-card-prod-ingress