app:
  env: dev
  name: bonfairplace-main
  namespace: argocd-testing
  project: dev-bonfairplace
  version: 0.0.307
values: |    
  ingress.enabled: true
  nginx.backend.reg: http://bonfairplace-auth-srv/
  nginx.backend.auth: http://bonfairplace-auth-srv/
  nginx.backend.mail: http://bonfairplace-mail-srv/
  nginx.backend.posts: http://bonfairplace-posts-srv/
  nginx.backend.photo: http://bonfairplace-photo-srv/
  nginx.backend.notification: http://bonfairplace-notification-srv/
  nginx.backend.settings: http://bonfairplace-web-settings-srv/